name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache dependencies (Optional, based on your project setup)
      - name: Cache Node Modules
        uses: actions/cache@v4.2.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project (if applicable)
      - name: Build Project
        run: npm run build

      # Step 6: Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 7: Authenticate with Firebase
      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login:ci --no-localhost

      # Step 8: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
