steps:
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    path: . # Use the root directory of the repository

- name: Set up Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18 # Ensure this matches the required Node.js version

- name: Install dependencies
  run: npm install
  working-directory: ./ # Use the root directory where package.json is located

- name: Build project
  run: npm run build
  working-directory: ./ # Use the root directory

- name: Deploy to Firebase Hosting
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: ${{ secrets.GITHUB_TOKEN }}
    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    channelId: live
    projectId: norah-design-web
  env:
    CI: true
